#!/bin/sh
DIR=$(dirname $0)

CDN='http://mirror.cogentco.com/pub/apache/hadoop/common/stable'
VERSION='2.6.0'
HD_DIR="hadoop-${VERSION}"
Tarball="$HD_DIR.tar.gz"
HD_LIB_DIR='/usr/local/lib/hadoop'
URL="${CDN}/${Tarball}"

test -d $HD_LIB_DIR && echo "Hadoop already installed" && exit 1

echo $URL

cd /tmp
curl -O "$URL"
tar -xvf $Tarball
mv -f $HD_DIR /usr/lib/
ln -fs /usr/lib/$HD_DIR $HD_LIB_DIR

echo "export HD_LIB_DIR=$HD_LIB_DIR" >> ~/.bashrc-local
echo "export PATH=\$PATH:\$HD_LIB_DIR/bin" >> ~/.bashrc-local