#!/bin/sh
DIR=$(dirname $0)

CDN='http://download.nextag.com/apache/spark/'

VERSION='1.4.0'
SPARK_DIR="spark-${VERSION}-bin-hadoop2.4"
TARBALL="$SPARK_DIR.tgz"
LIB_DIR="/usr/local/lib"
SPARK_LIB_DIR="$LIB_DIR/spark"

URL="$CDN/spark-$VERSION/$TARBALL"

test -d "$LIB_DIR/$SPARK_DIR" && echo "Spark already installed" && exit 1

cd /tmp
curl -O $URL
tar -xvf $TARBALL

cp -rf $SPARK_DIR $LIB_DIR
ln -fs $SPARK_DIR $SPARK_LIB_DIR
